/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testcal;

/**
 *
 * @author DjShujja
 */
public class CgpaGUI extends javax.swing.JFrame {
    int semester = 1;
     float total,sem1,sem2,sem3,sem4,sem5,sem6,sem7,sem8,sem9;
     int rollNo;
    /**
     * Creates new form CgpaGUI
     */
    public CgpaGUI(int rollNo) {
        initComponents();
        this.rollNo = rollNo;
        lbl_rollNo.setText("" +this.rollNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_gpa = new javax.swing.JTextField();
        btn_addSemester = new javax.swing.JButton();
        lbl_cgpa = new javax.swing.JLabel();
        total_cgpa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_rollNo = new javax.swing.JLabel();
        lbl_semester = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NUML GPA Calculator");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Enter GPA Of Semester");

        txt_gpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gpaActionPerformed(evt);
            }
        });

        btn_addSemester.setText("Next Semester");
        btn_addSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addSemesterActionPerformed(evt);
            }
        });

        lbl_cgpa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cgpa.setText("CGPA: ");

        total_cgpa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_cgpa.setText("0.00");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("WELCOME");

        lbl_rollNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_rollNo.setText("RollNo");

        lbl_semester.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_semester.setText("1");

        jButton1.setText("GO BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(lbl_cgpa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_cgpa))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(136, 136, 136)
                                    .addComponent(jLabel4)
                                    .addGap(39, 39, 39))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl_semester)
                                    .addGap(8, 8, 8)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_rollNo)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_gpa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_addSemester))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_rollNo))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_semester)
                    .addComponent(btn_addSemester))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cgpa)
                    .addComponent(total_cgpa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_gpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gpaActionPerformed

    private void btn_addSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addSemesterActionPerformed
        // TODO add your handling code here:
        
      
        
        System.out.println(semester);
          float cgpa;
        switch(semester){
            case 1:{
                
                sem1 =  Float.parseFloat(txt_gpa.getText());
                this.total += sem1;
                cgpa = total / semester;
                total_cgpa.setText("" + cgpa);
                System.out.println(cgpa + " is cgpa of semester " + semester);
                
                semester++;
                lbl_semester.setText("" + semester);
                break;
            }
            case 2:{
                
                sem2 = Float.parseFloat(txt_gpa.getText());
                 this.total += sem2;
                
                cgpa = total/semester;
                total_cgpa.setText("" + cgpa);
                System.out.println(cgpa + " is cgpa of semester " + semester);
                semester++;
                lbl_semester.setText("" + semester);
                break;
            }
             case 3:{
                 lbl_semester.setText("" + semester);
                 sem3 = Float.parseFloat(txt_gpa.getText());
                 this.total += sem3;
                
                cgpa = total/semester;
                total_cgpa.setText("" + cgpa);
                System.out.println(cgpa + " is cgpa of semester " + semester);
                semester++;
                lbl_semester.setText("" + semester);
                break;
            }
             case 4:{
                sem4 = Float.parseFloat(txt_gpa.getText());
                this.total += sem4;
                
                cgpa = total/semester;
                total_cgpa.setText("" + cgpa);
                System.out.println(cgpa + " is cgpa of semester " + semester);
                semester++;
                lbl_semester.setText("" + semester);
                break;
            }
             case 5:{
                sem5 = Float.parseFloat(txt_gpa.getText());
                this.total += sem5;
                
                cgpa = total/semester;
                total_cgpa.setText("" + cgpa);
                System.out.println(cgpa + " is cgpa of semester " + semester);
                semester++;
                lbl_semester.setText("" + semester);
                break;
            }
             case 6:{
                sem6 = Float.parseFloat(txt_gpa.getText());
                this.total += sem6;
                
                cgpa = total/semester;
                total_cgpa.setText("" + cgpa);
                System.out.println(cgpa + " is cgpa of semester " + semester);
                semester++;
                lbl_semester.setText("" + semester);
                break;
            }
             case 7:{
                sem7 = Float.parseFloat(txt_gpa.getText());
                this.total += sem7;
                
                cgpa = total/semester;
                total_cgpa.setText("" + cgpa);
                System.out.println(cgpa + " is cgpa of semester " + semester);
                semester++;
                lbl_semester.setText("" + semester);
                break;
            }
             case 8:{
                sem8 = Float.parseFloat(txt_gpa.getText());
                this.total += sem8;
                
                cgpa = total/semester;
                total_cgpa.setText("" + cgpa);
                System.out.println(cgpa + " is cgpa of semester " + semester);
                semester++;
                lbl_semester.setText("" + semester);
                break;
            }
             case 9:{
                sem9 = Float.parseFloat(txt_gpa.getText());
                this.total += sem9;
                
                cgpa = total/semester;
                total_cgpa.setText("" + cgpa);
                System.out.println(cgpa + " is cgpa of semester " + semester);
                semester++;
                lbl_semester.setText("" + semester);
                break;
            }
        }
    }//GEN-LAST:event_btn_addSemesterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ChoiceScreen(rollNo).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CgpaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CgpaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CgpaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CgpaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CgpaGUI(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addSemester;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_cgpa;
    private javax.swing.JLabel lbl_rollNo;
    private javax.swing.JLabel lbl_semester;
    private javax.swing.JLabel total_cgpa;
    private javax.swing.JTextField txt_gpa;
    // End of variables declaration//GEN-END:variables
}
